name: 'Google Drive Upload'
description: 'Upload files to Google Drive'
inputs:
  service_account_key_json:
    description: 'Google Service Account JSON Key'
    required: true
  folder_id:
    description: 'Google Drive folder ID where the file will be stored'
    required: true
  local_path:
    description: 'Path to the local file to upload'
    required: true
  remote_filename:
    description: 'Name of the file to create'
    required: false
    default: null
  subfolder_name:
    description: 'Name of a subfolder where the file will be created'
    required: false
    default: null
  overwrite:
    description: 'Whether to overwrite an existing file with the same name.'
    required: false
    default: false
  convert:
    description: 'Whether to convert files to Google Docs format (xlsx and csv only).'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
